version: "3.2"

networks:
  elk:
    external: true

services:
  loggen:
    image: angry-elk/loggen
    networks:
    - elk
    environment: []
    deploy:
      mode: global # Just so we get more logs :-)
      resources:
        limits:
          cpus: "1"
      restart_policy:
        condition: any
        delay: 30s
      placement:
        constraints:
        - node.role == worker
