version: "3.2"

networks:
  elk:
    external: true

services:
  logspout:
    image: angry-elk/logspout

    networks:
    - elk

    environment:
      ROUTE_URIS: 'logstash+tcp://logstash:5000'
      LOGSTASH_FIELDS: "type=docker"
      DOCKER_LABELS: "true"
      SYSLOG_FORMAT: "rfc3164"
      RETRY_STARTUP: "true"

    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
    - logstash

    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.4"
          memory: 512M
        reservations:
          cpus: "0.1"
      restart_policy:
        condition: any
        delay: 30s
