version: "3.2"

networks:
  elk:
    external: true

services:
  logstash:
    image: angry-elk/logstash
    networks:
    - elk
    environment:
      # This tells logspout not to capture logs from this container
      LOGSPOUT: 'ignore'
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 30s
      placement:
        constraints:
        - node.role == worker
